//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonBook {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PersonBookResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PersonBookResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PersonBook.PersonBookResources", typeof(PersonBookResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled error occured:
        ///{0}.
        /// </summary>
        public static string ApplicationError {
            get {
                return ResourceManager.GetString("ApplicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date cannot be empty.
        /// </summary>
        public static string DateValidationRule_DateEmpty {
            get {
                return ResourceManager.GetString("DateValidationRule_DateEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter date before now.
        /// </summary>
        public static string DateValidationRule_DateInvalid {
            get {
                return ResourceManager.GetString("DateValidationRule_DateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are 10 persons added already. Adding another person will remove one wich is outdated.
        ///Do you want to continue?.
        /// </summary>
        public static string MainViewModel_SaveCommand_Message {
            get {
                return ResourceManager.GetString("MainViewModel_SaveCommand_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string MainViewModel_SaveCommand_MessageTitle {
            get {
                return ResourceManager.GetString("MainViewModel_SaveCommand_MessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string MainWindow_ButtonAdd {
            get {
                return ResourceManager.GetString("MainWindow_ButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string MainWindow_ButtonCancel {
            get {
                return ResourceManager.GetString("MainWindow_ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string MainWindow_ButtonDelete {
            get {
                return ResourceManager.GetString("MainWindow_ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string MainWindow_ButtonEdit {
            get {
                return ResourceManager.GetString("MainWindow_ButtonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string MainWindow_ButtonSave {
            get {
                return ResourceManager.GetString("MainWindow_ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date:.
        /// </summary>
        public static string MainWindow_EditPanel_BirthDate {
            get {
                return ResourceManager.GetString("MainWindow_EditPanel_BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marital Status:.
        /// </summary>
        public static string MainWindow_EditPanel_MaritalStatus {
            get {
                return ResourceManager.GetString("MainWindow_EditPanel_MaritalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string MainWindow_EditPanel_Name {
            get {
                return ResourceManager.GetString("MainWindow_EditPanel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname:.
        /// </summary>
        public static string MainWindow_EditPanel_Surname {
            get {
                return ResourceManager.GetString("MainWindow_EditPanel_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        public static string MainWindow_MainDataGrid_CreationDate {
            get {
                return ResourceManager.GetString("MainWindow_MainDataGrid_CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string MainWindow_MainDataGrid_Name {
            get {
                return ResourceManager.GetString("MainWindow_MainDataGrid_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string MainWindow_MainDataGrid_Surname {
            get {
                return ResourceManager.GetString("MainWindow_MainDataGrid_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persons:.
        /// </summary>
        public static string MainWindow_MainDataGridTitle {
            get {
                return ResourceManager.GetString("MainWindow_MainDataGridTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure that your data is saved before importing new. All actual data will be overriden..
        /// </summary>
        public static string MainWindow_MessageBox_EnsureImportData {
            get {
                return ResourceManager.GetString("MainWindow_MessageBox_EnsureImportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Data.
        /// </summary>
        public static string MainWindow_MessageBox_EnsureImportDataTitle {
            get {
                return ResourceManager.GetString("MainWindow_MessageBox_EnsureImportDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Data.
        /// </summary>
        public static string MainWindow_MessageBox_ExportDataTitle {
            get {
                return ResourceManager.GetString("MainWindow_MessageBox_ExportDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your name.
        /// </summary>
        public static string MainWindow_NameTextBox_TargetNullValue {
            get {
                return ResourceManager.GetString("MainWindow_NameTextBox_TargetNullValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your surname.
        /// </summary>
        public static string MainWindow_SurnameTextBox_TargetNullValue {
            get {
                return ResourceManager.GetString("MainWindow_SurnameTextBox_TargetNullValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person Book.
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
    }
}
